id = "senkai-theme"
name = "Senkai"
version = "1.0.0"
schema_version = 1
authors = ["Andrew Sen <platformer@github.com>"]
description = "A dark theme with perceptually uniform syntax colors. Inspired by Seti Monokai and Penumbra from VS Code."
repository = "https://github.com/platformer/zed-senkai"
